# SCHEMA DEFINITION

type Link { 
    url: String!  # same as VARCHAR NOT NULL
    name: String!
    description: String!
    archived: Boolean
}

type Query{
    getAllLinks: [Link!]!  #Returns many links
}



# QUERY SAMPLE
# query {
#   getAllLinks{
#
##    DATA OBJ IS A GRAPHQL CONVETION
#     data{
#       name
#       url
#       description
#       archived
#       _id
#     }
#   }
# }

# MUTATION SAMPLE
# mutation {
##   CALLING DATA OBJ CREATION
#    createLink(
#     data: {
#     	name: "Test Link",
#     	url: "www.test.com",
#     	description: "Test sample",
#       archived: true,
	  }
#   )
##   WHAT OBJECT RETURNS
#   {
    #   name
    #   _id
# 	}
# }